site_name: FujiHack Wiki
site_url: https://wiki.fujihack.org/
site_description: Wiki for Fujihack, holding all information about the project
site_author: FujiHack Contributors

repo_url: https://github.com/fujihack/fujihack.github.io
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    scheme: slate

extra_css:
    - a.css

nav:
    - Home: index.md
    - Fujifilm Internals:
        - History overview: history.md
        - Firmware overview: rtos.md
        - AUTO ACT script: autoactscr.md
        - Key codes: keys.md
        - Tasks: tasks.md
        - PTP/USB: ptp.md
        - Syslog: syslog.md
        - Function signatures: signatures.md
        - EEPROM: eep.md
        - Firmware header: firmware.md
        - EXIF Info: exif.md
    - Development:
        - Vocabulary: words.md
        - Project Structure: structure.md 
        - Help Needed: todo.md
